(() => {
  if (location.protocol === 'file:') document.body.classList.add('local-file');
  const token = localStorage.getItem('storySproutToken');
  if (token) return;
  const gate = document.createElement('section');
  gate.className = 'auth-gate';
  gate.innerHTML = `<div class="auth-card"><div class="auth-brand"><span class="auth-mark"></span>Story Sprout</div><h1>Stories that grow with your reader.</h1><p>Parent and teacher accounts keep each learner's stories and progress private.</p><div class="auth-tabs"><button class="auth-tab active" data-mode="login">Sign in</button><button class="auth-tab" data-mode="register">Create account</button></div><form id="authForm"><div id="registerFields" class="hidden"><div class="auth-field"><label for="authName">Your name</label><input id="authName" maxlength="60" autocomplete="name"></div><div class="auth-field"><label for="authRole">Account type</label><select id="authRole"><option value="parent">Parent or guardian</option><option value="teacher">Teacher</option></select></div></div><div class="auth-field"><label for="authEmail">Email</label><input id="authEmail" type="email" maxlength="120" autocomplete="email" required></div><div class="auth-field"><label for="authPassword">Password</label><input id="authPassword" type="password" minlength="12" maxlength="128" autocomplete="current-password" required></div><label id="consentField" class="auth-consent hidden"><input id="authConsent" type="checkbox"> I am an adult and approve the use of learner profiles for this account.</label><button class="auth-submit" id="authSubmit">Sign in</button><div class="auth-error" id="authError" role="alert"></div></form><button class="auth-demo" id="demoButton">Continue with local demo</button><div class="auth-foot">Passwords are hashed on the server. Stories and learner data are protected by the signed-in adult account.</div></div>`;
  document.body.appendChild(gate);
  const $ = s => gate.querySelector(s); let mode = 'login';
  function setMode(next) { mode = next; gate.querySelectorAll('.auth-tab').forEach(button => button.classList.toggle('active', button.dataset.mode === mode)); $('#registerFields').classList.toggle('hidden', mode !== 'register'); $('#consentField').classList.toggle('hidden', mode !== 'register'); $('#authSubmit').textContent = mode === 'register' ? 'Create secure account' : 'Sign in'; $('#authPassword').autocomplete = mode === 'register' ? 'new-password' : 'current-password'; $('#authError').textContent = ''; }
  gate.querySelectorAll('.auth-tab').forEach(button => button.onclick = () => setMode(button.dataset.mode));
  $('#demoButton').onclick = () => gate.remove();
  $('#authForm').onsubmit = async event => { event.preventDefault(); const error = $('#authError'); error.textContent = ''; const body = { email: $('#authEmail').value.trim(), password: $('#authPassword').value }; if (mode === 'register') { if (!$('#authConsent').checked) { error.textContent = 'Guardian or adult consent is required.'; return; } Object.assign(body, { displayName: $('#authName').value.trim(), role: $('#authRole').value, guardianConsent: true }); } try { const response = await fetch(`/api/auth/${mode === 'register' ? 'register' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to sign in.'); localStorage.setItem('storySproutToken', result.token); localStorage.setItem('storySproutAccount', JSON.stringify(result.account)); location.reload(); } catch (requestError) { error.textContent = location.protocol === 'file:' ? 'Start the local server before signing in. Use the local demo for now.' : requestError.message; } };
})();
