(() => {
  if (location.protocol === 'file:') document.body.classList.add('local-file');
  const token = localStorage.getItem('storySproutToken');
  if (token) return;
  const gate = document.createElement('section');
  gate.className = 'auth-gate';
  gate.innerHTML = `<div class="auth-card"><div class="auth-brand"><span class="auth-mark"></span>Story Sprout</div><h1>Stories that grow with your reader.</h1><p>Parent and teacher accounts keep each learner's stories and progress private.</p><div class="auth-tabs"><button class="auth-tab active" data-mode="login">Sign in</button><button class="auth-tab" data-mode="register">Create account</button></div><form id="authForm"><div id="registerFields" class="hidden"><div class="auth-field"><label for="authName">Your name</label><input id="authName" minlength="2" maxlength="60" autocomplete="name"><small class="auth-help">Use 2–60 characters.</small></div><div class="auth-field"><label for="authRole">Account type</label><select id="authRole"><option value="parent">Parent or guardian</option><option value="teacher">Teacher</option></select></div></div><div class="auth-field"><label for="authEmail">Email</label><input id="authEmail" type="email" maxlength="120" autocomplete="email" placeholder="you@example.com" required><small class="auth-help">Use a valid email address.</small></div><div class="auth-field"><label for="authPassword">Password</label><input id="authPassword" type="password" minlength="6" maxlength="128" autocomplete="current-password" required><small class="auth-help">Use at least 6 characters.</small></div><button type="button" class="auth-link hidden" id="forgotPassword">Forgot password?</button><label id="consentField" class="auth-consent hidden"><input id="authConsent" type="checkbox"> I am an adult parent, guardian, or authorized educator. I approve learner profiles, have reviewed the Privacy Policy and Terms of Service, and consent to AI story generation for this account.</label><button class="auth-submit" id="authSubmit">Sign in</button><div class="auth-error" id="authError" role="alert"></div></form><button class="auth-demo" id="demoButton">Continue with local demo</button><div class="auth-foot">Passwords are hashed on the server. Stories and learner data are protected by the signed-in adult account.</div></div>`;
  document.body.appendChild(gate);
  gate.querySelectorAll('.auth-tab').forEach(button => { button.type = 'button'; });
  gate.querySelector('.auth-card h1').textContent = 'Create personalized reading stories for your child.';
  gate.querySelector('.auth-card h1 + p').textContent = "Parents, guardians, and teachers use Story Sprout to turn a learner's interests into stories that build reading skills, confidence, and conversation.";
  const $ = s => gate.querySelector(s); let mode = 'login';
  document.addEventListener('input', event => {
    if (event.target.id !== 'authPassword' && event.target.id !== 'authConfirmPassword' && event.target.id !== 'resetPassword' && event.target.id !== 'resetConfirmPassword') return;
    const password = document.querySelector('#authPassword, #resetPassword');
    const confirmation = document.querySelector('#authConfirmPassword, #resetConfirmPassword');
    if (password && confirmation) confirmation.setCustomValidity(password.value === confirmation.value ? '' : 'Passwords must match.');
  });
  const confirmField = document.createElement('div');
  confirmField.id = 'confirmPasswordField';
  confirmField.className = 'auth-field hidden';
  confirmField.innerHTML = '<label for="authConfirmPassword">Confirm password</label><input id="authConfirmPassword" type="password" minlength="6" maxlength="128" autocomplete="new-password"><small class="auth-help">Passwords must match.</small>';
  confirmField.querySelector('#authConfirmPassword').required = false;
  $('#authPassword').closest('.auth-field').after(confirmField);
  const resetToken = new URLSearchParams(location.search).get('resetToken');
  if (resetToken) {
    $('.auth-card').innerHTML = '<div class="auth-brand"><span class="auth-mark"></span>Story Sprout</div><h1>Choose a new password.</h1><p>Use at least 6 characters. This reset link can be used once and expires after 30 minutes.</p><form id="resetForm"><div class="auth-field"><label for="resetPassword">New password</label><input id="resetPassword" type="password" minlength="6" maxlength="128" autocomplete="new-password" required></div><div class="auth-field"><label for="resetConfirmPassword">Confirm new password</label><input id="resetConfirmPassword" type="password" minlength="6" maxlength="128" autocomplete="new-password" required></div><button class="auth-submit">Update password</button><div class="auth-error" id="resetError" role="alert"></div></form></div>';
    $('#resetForm').onsubmit = async event => { event.preventDefault(); const error = $('#resetError'); try { const response = await fetch('/api/auth/reset-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token: resetToken, password: $('#resetPassword').value }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to reset password.'); error.textContent = result.message; setTimeout(() => { history.replaceState({}, '', location.pathname); location.reload(); }, 1200); } catch (requestError) { error.textContent = requestError.message; } };
    return;
  }
  function setMode(next) { mode = next; gate.querySelectorAll('.auth-tab').forEach(button => button.classList.toggle('active', button.dataset.mode === mode)); $('#registerFields').classList.toggle('hidden', mode !== 'register'); $('#consentField').classList.toggle('hidden', mode !== 'register'); $('#confirmPasswordField').classList.toggle('hidden', mode !== 'register'); $('#authConfirmPassword').required = mode === 'register'; $('#authConfirmPassword').disabled = mode !== 'register'; $('#forgotPassword').classList.toggle('hidden', mode !== 'login'); $('#authSubmit').textContent = mode === 'register' ? 'Create secure account' : 'Sign in'; $('#authPassword').autocomplete = mode === 'register' ? 'new-password' : 'current-password'; $('#authError').textContent = ''; }
  setMode('login');
  gate.querySelector('#authForm').addEventListener('submit', event => { if (mode === 'register' && $('#authPassword').value !== $('#authConfirmPassword').value) { event.preventDefault(); event.stopImmediatePropagation(); $('#authError').textContent = 'Passwords must match.'; } }, true);
  gate.querySelectorAll('.auth-tab').forEach(button => button.onclick = () => setMode(button.dataset.mode));
  $('#forgotPassword').onclick = async () => { const email = $('#authEmail').value.trim(); if (!email) { $('#authError').textContent = 'Enter your email first.'; return; } try { const response = await fetch('/api/auth/forgot-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to send reset link.'); $('#authError').textContent = result.message; } catch (error) { $('#authError').textContent = error.message; } };
  function showVerificationPrompt(message) { $('#authError').textContent = message; let button = gate.querySelector('#resendVerification'); if (!button) { button = document.createElement('button'); button.id = 'resendVerification'; button.type = 'button'; button.className = 'auth-link'; button.textContent = 'Resend verification email'; $('#authError').after(button); button.onclick = async () => { try { const response = await fetch('/api/auth/resend-verification', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: $('#authEmail').value.trim() }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to resend verification email.'); $('#authError').textContent = result.message; } catch (error) { $('#authError').textContent = error.message; } }; } }
  $('#demoButton').onclick = () => gate.remove();
  $('#authForm').onsubmit = async event => { event.preventDefault(); const error = $('#authError'); error.textContent = ''; const body = { email: $('#authEmail').value.trim(), password: $('#authPassword').value }; if (mode === 'register') { if (!$('#authConsent').checked) { error.textContent = 'Adult and external AI consent is required.'; return; } Object.assign(body, { displayName: $('#authName').value.trim(), role: $('#authRole').value, guardianConsent: true, aiExternalConsent: true }); } try { const response = await fetch(`/api/auth/${mode === 'register' ? 'register' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (result.code === 'EMAIL_NOT_VERIFIED' || result.verificationRequired) { showVerificationPrompt(result.message || result.error); return; } if (!response.ok) throw new Error(result.error || 'Unable to sign in.'); localStorage.setItem('storySproutToken', result.token); localStorage.setItem('storySproutAccount', JSON.stringify(result.account)); location.reload(); } catch (requestError) { error.textContent = location.protocol === 'file:' ? 'Start the local server before signing in. Use the local demo for now.' : requestError.message; } };
})();
