(() => {
  if (location.protocol === 'file:') document.body.classList.add('local-file');
  const token = localStorage.getItem('storySproutToken');
  const cancelSubscriptionToken = new URLSearchParams(location.search).get('cancelSubscriptionToken');
  if (cancelSubscriptionToken) {
    fetch('/api/auth/confirm-subscription-cancellation', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token: cancelSubscriptionToken }) })
      .then(response => response.ok ? response.json() : response.json().then(data => Promise.reject(new Error(data.error || 'Cancellation confirmation failed.'))))
      .then(result => { history.replaceState({}, '', location.pathname); document.body.innerHTML = `<main style="font-family:Arial,sans-serif;padding:40px;color:#173b42"><h1>Subscription canceled</h1><p>${result.message}</p><p>Your learner profiles, stories, and reading progress remain saved.</p><a href="/">Return to StoryAura Land</a></main>`; })
      .catch(error => { document.body.innerHTML = `<main style="font-family:Arial,sans-serif;padding:40px;color:#173b42"><h1>Cancellation confirmation failed</h1><p>${error.message}</p></main>`; });
    return;
  }
  const deleteAccountToken = new URLSearchParams(location.search).get('deleteAccountToken');
  if (deleteAccountToken) {
    fetch('/api/auth/confirm-account-deletion', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token: deleteAccountToken }) })
      .then(response => response.ok ? response.text() : response.json().then(data => Promise.reject(new Error(data.error || 'Deletion confirmation failed.'))))
      .then(() => { ['storySproutToken', 'storySproutAccount', 'storySproutEnterprise', 'storySproutProfile', 'storySproutBooksV2', 'storySproutBooks'].forEach(key => localStorage.removeItem(key)); history.replaceState({}, '', location.pathname); document.body.innerHTML = '<main style="font-family:Arial,sans-serif;padding:40px;color:#173b42"><h1>Account deleted</h1><p>Your StoryAura Land account and learner data were permanently deleted.</p></main>'; })
      .catch(error => { document.body.innerHTML = `<main style="font-family:Arial,sans-serif;padding:40px;color:#173b42"><h1>Deletion confirmation failed</h1><p>${error.message}</p></main>`; });
    return;
  }
  if (token) return;
  const gate = document.createElement('section');
  gate.className = 'auth-gate';
  gate.innerHTML = `<div class="auth-card"><button type="button" class="auth-close" id="authClose" aria-label="Close">&times;</button><div class="auth-brand"><span class="auth-mark"></span>StoryAura Land</div><div class="auth-visual"><img src="images/storyaura-kids-blanket.jpg" alt="Child reading under a blanket"></div><h1>Stories that grow with your reader.</h1><p>Parents create child logins so learners can sign in without the parent account and read together on a computer or tablet.</p><div class="auth-tabs"><button class="auth-tab active" data-mode="login">Parent sign in</button><button class="auth-tab" data-mode="child-login">Child sign in</button><button class="auth-tab" data-mode="register">Create account</button></div><form id="authForm"><div id="registerFields" class="hidden"><div class="auth-field"><label for="authName">Your name</label><input id="authName" minlength="2" maxlength="60" autocomplete="name"><small class="auth-help">Use 2–60 characters.</small></div><div class="auth-field"><label for="authRole">Account type</label><select id="authRole"><option value="parent">Parent or guardian</option><option value="teacher">Teacher</option></select></div></div><div class="auth-field"><label id="authIdentityLabel" for="authEmail">Email</label><input id="authEmail" type="email" maxlength="120" autocomplete="email" placeholder="you@example.com" required><small class="auth-help" id="authIdentityHelp">Use the parent account email.</small></div><div class="auth-field"><label for="authPassword">Password</label><input id="authPassword" type="password" minlength="6" maxlength="128" autocomplete="current-password" required><small class="auth-help">Use at least 6 characters.</small></div><button type="button" class="auth-link hidden" id="forgotPassword">Forgot password?</button><label id="consentField" class="auth-consent hidden"><input id="authConsent" type="checkbox"> I am an adult parent, guardian, or authorized educator. I approve learner profiles, have reviewed the Privacy Policy and Terms of Service, and consent to AI story generation for this account.</label><div id="signupReveal" class="auth-reveal hidden"><strong>Hidden scene preview</strong><p>Unlock the full moonseed branch and the private reading goals after your account is created.</p></div><button class="auth-submit" id="authSubmit">Sign in</button><div class="auth-error" id="authError" role="alert"></div></form><button class="auth-demo" id="demoButton">Continue browsing without an account</button><div class="auth-foot">Parents manage child usernames and passwords from the parent workspace.</div></div>`;
  document.body.appendChild(gate);
  const logoStyle = document.createElement('style');
  logoStyle.textContent = '.auth-mark{position:relative;background-color:#db6f47;background-image:radial-gradient(circle at 5px 9px,#fff7ea 0 2px,transparent 2.5px),radial-gradient(circle at 13px 6px,#fff7ea 0 2px,transparent 2.5px),radial-gradient(circle at 19px 6px,#fff7ea 0 2px,transparent 2.5px),radial-gradient(circle at 26px 9px,#fff7ea 0 2px,transparent 2.5px),radial-gradient(ellipse at 5px 17px,#fff7ea 0 3px,transparent 3.5px),radial-gradient(ellipse at 13px 14px,#fff7ea 0 3px,transparent 3.5px),radial-gradient(ellipse at 19px 14px,#fff7ea 0 3px,transparent 3.5px),radial-gradient(ellipse at 26px 17px,#fff7ea 0 3px,transparent 3.5px)}.auth-mark:after{content:"";position:absolute;width:8px;height:11px;border:2px solid #db6f47;border-left-color:#fff7ea;border-bottom-color:#fff7ea;border-radius:100% 0;left:11px;top:15px;transform:rotate(35deg);background:#fff7ea}';
  document.head.appendChild(logoStyle);
  const consentStyle = document.createElement('style');
  consentStyle.textContent = '.auth-consent{display:flex;align-items:flex-start;gap:10px;padding:12px;border:1px solid #e5d5bf;border-radius:6px;background:#fff8ed}.auth-consent input{flex:0 0 auto;width:18px;height:18px;margin:1px 0 0;accent-color:#2f6c50}.auth-visual{margin:14px 0 18px;border-radius:18px;overflow:hidden;border:1px solid #e7d8c2;background:#f8f1e6;box-shadow:0 10px 24px rgba(20,48,55,.08)}.auth-visual img{display:block;width:100%;height:180px;object-fit:cover}.auth-visual:after{content:"Parents can create and read together.";display:block;padding:10px 14px;font:700 12px/1.3 Arial,sans-serif;color:#4d6668;background:linear-gradient(135deg,#eef6ec,#fff7ea)}';
  document.head.appendChild(consentStyle);
  const revealStyle = document.createElement('style');
  revealStyle.textContent = '.auth-reveal{margin:16px 0 8px;padding:14px 16px;border-radius:8px;background:linear-gradient(135deg,#edf6ec,#fff5dd);border:1px solid #d7d0ba}.auth-reveal strong{display:block;font:700 11px Arial,sans-serif;letter-spacing:1.2px;text-transform:uppercase;color:#48645c;margin-bottom:4px}.auth-reveal p{margin:0;color:#39525a;font:14px/1.45 Arial,sans-serif}';
  document.head.appendChild(revealStyle);
  gate.querySelectorAll('.auth-tab').forEach(button => { button.type = 'button'; });
  gate.querySelector('.auth-card h1').textContent = 'Create personalized reading stories for your child.';
  gate.querySelector('.auth-card h1 + p').textContent = "Parents, guardians, and teachers use StoryAura Land to turn a learner's interests into stories that build reading skills, confidence, and conversation.";
  const sampleSignupTeaser = sessionStorage.getItem('storyAuraLandTeaserSource') === 'sample-story';
  const $ = s => gate.querySelector(s); let mode = 'login';
  document.addEventListener('input', event => {
    if (event.target.id !== 'authPassword' && event.target.id !== 'authConfirmPassword' && event.target.id !== 'resetPassword' && event.target.id !== 'resetConfirmPassword') return;
    const password = document.querySelector('#authPassword, #resetPassword');
    const confirmation = document.querySelector('#authConfirmPassword, #resetConfirmPassword');
    if (password && confirmation) confirmation.setCustomValidity(password.value === confirmation.value ? '' : 'Passwords must match.');
  });
  const confirmField = document.createElement('div');
  confirmField.id = 'confirmPasswordField';
  confirmField.className = 'auth-field hidden';
  confirmField.innerHTML = '<label for="authConfirmPassword">Confirm password</label><input id="authConfirmPassword" type="password" minlength="6" maxlength="128" autocomplete="new-password"><small class="auth-help">Passwords must match.</small>';
  confirmField.querySelector('#authConfirmPassword').required = false;
  $('#authPassword').closest('.auth-field').after(confirmField);
  const resetToken = new URLSearchParams(location.search).get('resetToken');
  if (resetToken) {
    $('.auth-card').innerHTML = '<div class="auth-brand"><span class="auth-mark"></span>StoryAura Land</div><h1>Choose a new password.</h1><p>Use at least 6 characters. This reset link can be used once and expires after 30 minutes.</p><form id="resetForm"><div class="auth-field"><label for="resetPassword">New password</label><input id="resetPassword" type="password" minlength="6" maxlength="128" autocomplete="new-password" required></div><div class="auth-field"><label for="resetConfirmPassword">Confirm new password</label><input id="resetConfirmPassword" type="password" minlength="6" maxlength="128" autocomplete="new-password" required></div><button class="auth-submit">Update password</button><div class="auth-error" id="resetError" role="alert"></div></form></div>';
    $('#resetForm').onsubmit = async event => { event.preventDefault(); const error = $('#resetError'); try { const response = await fetch('/api/auth/reset-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token: resetToken, password: $('#resetPassword').value }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to reset password.'); error.textContent = result.message; setTimeout(() => { history.replaceState({}, '', location.pathname); location.reload(); }, 1200); } catch (requestError) { error.textContent = requestError.message; } };
    return;
  }
  function setMode(next) { mode = next; const childMode = mode === 'child-login'; const registerMode = mode === 'register'; gate.querySelectorAll('.auth-tab').forEach(button => button.classList.toggle('active', button.dataset.mode === mode)); $('#registerFields').classList.toggle('hidden', !registerMode); $('#consentField').classList.toggle('hidden', !registerMode); $('#confirmPasswordField').classList.toggle('hidden', !registerMode); $('#signupReveal').classList.toggle('hidden', !(registerMode && sampleSignupTeaser)); $('#authConfirmPassword').required = registerMode; $('#authConfirmPassword').disabled = !registerMode; $('#forgotPassword').classList.toggle('hidden', mode !== 'login'); $('#authSubmit').textContent = registerMode ? 'Create secure account' : childMode ? 'Child sign in' : 'Parent sign in'; $('#authPassword').autocomplete = registerMode ? 'new-password' : 'current-password'; $('#authEmail').type = childMode ? 'text' : 'email'; $('#authEmail').placeholder = childMode ? 'your child username' : 'you@example.com'; $('#authIdentityLabel').textContent = childMode ? 'Child username' : 'Email'; $('#authIdentityHelp').textContent = childMode ? 'Use the username created by your parent.' : 'Use the parent account email.'; if (registerMode && sampleSignupTeaser) { $('#signupReveal').querySelector('p').textContent = 'This is the hidden scene your child will see after signup: the moonseed opens a secret door and the story keeps going in private.'; } $('#authError').textContent = ''; }
  setMode('login');
  gate.querySelector('#authForm').addEventListener('submit', event => { if (mode === 'register' && $('#authPassword').value !== $('#authConfirmPassword').value) { event.preventDefault(); event.stopImmediatePropagation(); $('#authError').textContent = 'Passwords must match.'; } }, true);
  gate.querySelectorAll('.auth-tab').forEach(button => button.onclick = () => setMode(button.dataset.mode));
  $('#forgotPassword').onclick = async () => { const email = $('#authEmail').value.trim(); if (!email) { $('#authError').textContent = 'Enter your email first.'; return; } try { const response = await fetch('/api/auth/forgot-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to send reset link.'); $('#authError').textContent = result.message; } catch (error) { $('#authError').textContent = error.message; } };
  function showVerificationPrompt(message) { $('#authError').textContent = message; let button = gate.querySelector('#resendVerification'); if (!button) { button = document.createElement('button'); button.id = 'resendVerification'; button.type = 'button'; button.className = 'auth-link'; button.textContent = 'Resend verification email'; $('#authError').after(button); button.onclick = async () => { try { const response = await fetch('/api/auth/resend-verification', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: $('#authEmail').value.trim() }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to resend verification email.'); $('#authError').textContent = result.message; } catch (error) { $('#authError').textContent = error.message; } }; } }
  $('#demoButton').onclick = () => gate.remove();
  $('#authForm').onsubmit = async event => { event.preventDefault(); const error = $('#authError'); error.textContent = ''; const identity = $('#authEmail').value.trim(); const body = mode === 'child-login' ? { username: identity, password: $('#authPassword').value } : { email: identity, password: $('#authPassword').value }; if (mode === 'register') { if (!$('#authConsent').checked) { error.textContent = 'Adult and external AI consent is required.'; return; } Object.assign(body, { displayName: $('#authName').value.trim(), role: $('#authRole').value, guardianConsent: true, aiExternalConsent: true }); } const endpoint = mode === 'register' ? 'register' : mode === 'child-login' ? 'child-login' : 'login'; try { const response = await fetch(`/api/auth/${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (result.code === 'EMAIL_NOT_VERIFIED' || result.verificationRequired) { showVerificationPrompt(result.message || result.error); return; } if (!response.ok) throw new Error(result.error || 'Unable to sign in.'); localStorage.setItem('storySproutToken', result.token); localStorage.setItem('storySproutAccount', JSON.stringify(result.account)); if (mode === 'register' && sampleSignupTeaser) { $('#signupReveal').classList.remove('hidden'); $('#signupReveal').querySelector('strong').textContent = 'Hidden scene unlocked'; $('#signupReveal').querySelector('p').textContent = 'Your private story shelf is ready. The full moonseed branch will now appear inside the signed-in experience.'; $('#authSubmit').textContent = 'Opening your private story shelf...'; setTimeout(() => location.reload(), 1300); return; } location.reload(); } catch (requestError) { error.textContent = location.protocol === 'file:' ? 'Start the local server before signing in. Use the local demo for now.' : requestError.message; } };
})();
(() => {
  const gate = document.querySelector('.auth-gate');
  if (!gate) return;
  const forceOpen = new URLSearchParams(location.search).has('resetToken');
  if (!forceOpen) gate.classList.add('auth-gate-hidden');
  const closeGate = () => gate.classList.add('auth-gate-hidden');
  const openGate = mode => { gate.classList.remove('auth-gate-hidden'); gate.querySelector(`.auth-tab[data-mode="${mode}"]`)?.click(); };
  gate.querySelector('#authClose')?.addEventListener('click', closeGate);
  gate.addEventListener('click', event => { if (event.target === gate) closeGate(); });
  document.getElementById('demoButton')?.addEventListener('click', () => {
    document.getElementById('landingView')?.classList.remove('hidden');
  });
  document.querySelectorAll('[data-auth-open]').forEach(button => {
    button.addEventListener('click', () => openGate(button.dataset.authOpen || 'login'));
  });
})();
