import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import express from 'express';
import { newDb, DataType } from 'pg-mem';
import { createReadingRouter } from '../server/modules/reading-experience.js';
import { createAuthentication } from '../server/modules/authentication.js';

test('reading session and observation journey persists independently from assessment evidence', async t => {
  const db = newDb();
  db.public.registerFunction({ name: 'greatest', args: [DataType.integer, DataType.integer], returns: DataType.integer, implementation: Math.max });
  db.public.none(`CREATE TABLE accounts (id UUID PRIMARY KEY, role TEXT, email_verified_at TIMESTAMPTZ); CREATE TABLE learners (id UUID PRIMARY KEY, account_id UUID REFERENCES accounts(id)); CREATE TABLE stories (id UUID PRIMARY KEY, learner_id UUID REFERENCES learners(id), title TEXT, content JSONB, completed_at TIMESTAMPTZ, deleted_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW()); CREATE TABLE reading_assessments (id UUID PRIMARY KEY, story_id UUID REFERENCES stories(id), score INT, standards_evidence JSONB, review_status TEXT, created_at TIMESTAMPTZ DEFAULT NOW());`);
  db.public.none(await readFile(new URL('../server/migrations/010_reading_experience.sql', import.meta.url), 'utf8'));
  const { Pool } = db.adapters.createPg(); const pool = new Pool();
  const accountId=randomUUID(), learnerId=randomUUID(), storyId=randomUUID(), sessionId=randomUUID();
  await pool.query("INSERT INTO accounts VALUES ($1, 'parent', NOW())", [accountId]);
  await pool.query('INSERT INTO learners (id, account_id) VALUES ($1, $2)', [learnerId, accountId]);
  await pool.query('INSERT INTO stories (id, learner_id, title, content) VALUES ($1, $2, $3, $4)', [storyId, learnerId, 'The Map', { pages: ['A map.'] }]);
  const auth=createAuthentication({ pool, jwtSecret: 'isolated-test-secret-with-more-than-32-characters' });
  const app=express(); app.use(express.json()); app.use('/api/reading', auth.requireAuth, createReadingRouter({pool, requireAdultAccount: auth.requireAdultAccount}));
  app.use((err,req,res,next) => res.status(500).json({error:err.message}));
  const server=app.listen(0,'127.0.0.1'); await once(server,'listening'); t.after(() => {server.closeAllConnections(); server.close(); pool.end();});
  const token=auth.tokenFor({id:accountId,role:'parent'});
  const request=async(path,body) => {const response=await fetch(`http://127.0.0.1:${server.address().port}/api/reading${path}`,{method:body?'PUT':'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}); const data=await response.json(); assert.equal(response.status,200,JSON.stringify(data)); return data;};
  await request(`/stories/${storyId}/session`,{sessionId,activeSeconds:25});
  await request(`/stories/${storyId}/session`,{sessionId,activeSeconds:15});
  await request(`/stories/${storyId}/session`,{sessionId,activeSeconds:45});
  await request(`/stories/${storyId}/observation`,{assistance:'some_help',note:'Used the text to explain a choice.'});
  let snapshot=await request(`/learners/${learnerId}`);
  assert.equal(snapshot.activeSeconds,45,'retry and stale saves must not double-count or roll back time');
  assert.equal(snapshot.assessments.length,0,'adult observation must not invent an assessment');
  assert.equal(snapshot.observations[0].assistance,'some_help');
  assert.equal(snapshot.continueStory.id,storyId);
  await pool.query('INSERT INTO reading_assessments (id, story_id, score, standards_evidence, review_status) VALUES ($1,$2,67,$3,$4)',[randomUUID(),storyId,{correct:2,questionCount:3},'auto_scored']);
  await pool.query('UPDATE stories SET completed_at = NOW() WHERE id = $1',[storyId]);
  snapshot=await request(`/learners/${learnerId}`);
  assert.equal(snapshot.assessments[0].standards_evidence.correct,2);
  assert.equal(snapshot.continueStory,null);
  assert.equal(snapshot.observations[0].note,'Used the text to explain a choice.');
});
